config/routes.rb
Rails.application.routes.draw do

  resources :applications

  resources :comments
  resources :orders
  
  resources :items do
    resources :orders
    resources :comments
  end
  
  resources :orders do
    member do
      put "ship", to: "orders#ship"
    end
  end
  
  
  get 'users/show'

  devise_for :users
  
  resources :users
  resources :users do
    member do
      put "join", to: "users#join"
      put "kick", to: "users#kick"
    end
  end

  post "/orders/:id" => "orders#show"
  post "/hook" => "orders#hook"
  
  
  get 'pages/men'
  
  get 'pages/women'
  
  get 'pages/lookbook'
  
  get 'pages/manage'
  
  get 'pages/home'

  get 'pages/about'

  get 'pages/contact'
  
  get 'pages/shop'
  
  get 'pages/join'
  
  get 'pages/meet'
  
  root 'pages#home'
  
   get 'sales' => 'orders#sales'
  
  get 'purchases' => 'orders#purchases'

end

app/views/pages/_side.html.erb
<div class="well">  
           <h4>This Month's Clique</h4><hr>
  
  <div class="panel panel-default">
    <div class="panel-body">
      <%= link_to "WOMEN", pages_women_path %><br>
    </div>
    <div class="panel-body">
      <%= link_to "MEN", pages_men_path %><br>
    </div>
    <div class="panel-body">
      <%= link_to "LOOKBOOK", pages_lookbook_path %><br>
    </div>

  </div>
  
  
   </div>
      

app/views/pages/contact.html.erb
 <div class="text-center">
   <h3>To get in touch, simply send us a message at</h3>
   <h1>info@beencliqued.com</h1>
</div>

app/views/pages/lookbook.html.erb
<!-- Carousel
    ================================================== -->
    <div id="myCarousel" class="carousel slide" data-ride="carousel">
      <!-- Indicators -->
      <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
      </ol>
      <div class="carousel-inner" role="listbox">
        <div class="item active">
          <img src="http://placehold.it/1800x650/000000" class="img-responsive" style="width:100%" alt="First slide">
          <div class="container">
            <div class="carousel-caption">
            </div>
          </div>
        </div>
        <div class="item">
          <img src="http://placehold.it/1800x650/000000" class="img-responsive" style="width:100%"  alt="Second slide">
          <div class="container">
            <div class="carousel-caption">
            </div>
          </div>
        </div>
        <div class="item">
          <img src="http://placehold.it/1800x650/000000" class="img-responsive" style="width:100%"  alt="Third slide">
          <div class="container">
            <div class="carousel-caption">
            </div>
          </div>
        </div>
      </div>
      <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div><!-- /.carousel -->

app/views/pages/manage.html.erb
<div class="col-md-6 col-md-offset-3 text-center">
      <ul class="list-group">
      <% @users.each do |user|  %>

        <li class="list-group-item"><h3> <%=link_to user.email, user%> </h3>
            <% if user.member? %>
                <div class="btn btn-warning">Clique Member</div>
                
            <% else %>
                <div class="btn btn-default">Not a Member</div>
            <% end %>

        </li>

      <%end %>

      </ul>
</div>

app/views/pages/meet.html.erb
<div class="grid">
        <% @users.each do |user| %>

              <figure class="effect-bubba">
                
                <%= link_to  image_tag(user.image.url(:wide), width: "100%"), user%> 
                <figcaption>
                  <h2><span><%= user.name %> </span></h2>
                  <%= link_to "View this Store", user %>
                </figcaption>
                		
              </figure>
           
       <% end %>

</div>

app/views/pages/men.html.erb
<h1 style="text-align:center">Items for Men</h1>
 <div class="col-md-3">
      <%= render 'side' %>
    </div><!-----colmd3---->


<div class="col-md-9">
    <div class="grid">
      <% @items.each do |item| %>
            <div class="col-md-6">
                  <figure class="effect-zoe">

                   <%= link_to  image_tag(item.image.url(:display), width: "100%") %>
                    <figcaption>
                      <h2><%= link_to item.name, item%></h2>
                      <p class="icon-links">
                        <a href="#"><i class="fa fa-eye"></i></a>
                      </p>
                      <%= link_to "View this Store", item %>
                    </figcaption>

                  </figure>
      </div>
           <% end %>


    </div>
</div><!-----colmd9---->

app/views/pages/shop.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <%= render 'side' %>
    </div><!-----colmd3---->
    
    <div class="col-md-9">

                <!-- Carousel
            ================================================== -->
            <div id="myCarousel" class="carousel slide" data-ride="carousel">
              <!-- Indicators -->
              <ol class="carousel-indicators">
                <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
                <li data-target="#myCarousel" data-slide-to="1"></li>
                <li data-target="#myCarousel" data-slide-to="2"></li>
              </ol>
              <div class="carousel-inner" role="listbox">
                <div class="item active">
                  <img src="http://placehold.it/847x300/000000" alt="First slide">
                  <div class="container">
                  </div>
                </div>
                <div class="item">
                  <img src="http://placehold.it/847x300/000000" alt="Second slide">
                  <div class="container">
                  </div>
                </div>
                <div class="item">
                  <img src="http://placehold.it/847x300/000000" alt="Third slide">
                  <div class="container"> 
                  </div>
                </div>
              </div>
              <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
                <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
              </a>
              <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
                <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
              </a>
            </div><!-- /.carousel -->
            <br><br>
        
      <!-- picture box -->
      
             <img src="http://placehold.it/847x300/000000"  class="img-responsive" alt="Second slide">      
        </div>
      <!--/ picture box -->
      
    </div>
    
   
    
</div>

app/views/pages/women.html.erb
<h1 style="text-align:center">Items for Women</h1>
 <div class="col-md-3">
      <%= render 'side' %>
    </div><!-----colmd3---->


<div class="col-md-9">
    <div class="grid">
      <% @items.each do |item| %>
            <div class="col-md-3">
                  <figure class="effect-zoe">

                   <%= link_to  image_tag(item.image.url(:display), width: "100%") %>
                    <figcaption>
                      <h2><%= link_to item.name, item%></h2>
                      <p class="icon-links">
                        <a href="#"><i class="fa fa-eye"></i></a>
                      </p>
                      <%= link_to "View this Store", item %>
                    </figcaption>

                  </figure>
      </div>
           <% end %>


    </div>
</div><!-----colmd9---->