config/routes.rb
Rails.application.routes.draw do

  resources :applications

  resources :comments
  resources :orders
  
  resources :items do
    resources :orders
    resources :comments
  end
  
  resources :orders do
    member do
      put "ship", to: "orders#ship"
    end
  end
  
  
  get 'users/show'

  devise_for :users
  
  resources :users
  resources :users do
    member do
      put "join", to: "users#join"
      put "kick", to: "users#kick"
    end
  end

  post "/orders/:id" => "orders#show"
  post "/hook" => "orders#hook"
  
  
  get 'pages/men'
  
  get 'pages/women'
  
  get 'pages/lookbook'
  
  get 'pages/manage'
  
  get 'pages/home'

  get 'pages/about'

  get 'pages/contact'
  
  get 'pages/shop'
  
  get 'pages/join'
  
  get 'pages/meet'
  
  root 'pages#home'
  
   get 'sales' => 'orders#sales'
  
  get 'purchases' => 'orders#purchases'

end

app/models/item.rb
class Item < ActiveRecord::Base
 # include Payola::Sellable
  
  
  validates :name, :description, :price, :image, presence: true
  validates :price, numericality:{ greater_than: 0}  
  mount_uploader :image, ImageUploader
  belongs_to :user
  has_many :comments
  
 
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_filter :check_member, only: [:new, :create, :edit, :update, :destroy]
  before_filter :check_user, only: [:edit, :update, :destroy]
  

  respond_to :html

  def index
    @items = Item.all
    respond_with(@items)
  end

  def show
    respond_with(@item)
  end

  def new
    @item = Item.new
    respond_with(@item)
  end

  def edit
  end

  def create
    @item = Item.new(item_params)
    @item.user_id=current_user.id
    @item.save
    respond_with(@item)
  end

  def update
    @item.update(item_params)
    respond_with(@item)
  end

  def destroy
    @item.destroy
    respond_with(@item)
  end

  private
    def set_item
      @item = Item.find(params[:id])
    end

    def item_params
      params.require(:item).permit(:name, :description, :image, :category, :user_id, :price, :gender, :permalink)
    end
    def check_user
      if current_user != @item.user
        redirect_to root_url, alert: "Sorry, this Item belongs to someone else"\
        end
    end
    def check_member
      if current_user.member != true
        redirect_to new_application_path, alert: "You must be a Clique Member to do this"\
      end
    end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= form_for(@item) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name , class: "form-control", required:"true"%>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description, class: "form-control", required:"true" %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image , class: "form-control"%>
  </div>

  <div class="field">
    <%= f.label :category %><br>
    <%= f.select :category, ['Outerwear', 'Jackets', 'Dresses', 'Jumpsuits', 'Tops', 'Pants', 'Jeans', 'Skirts', 'T-Shirts', 'Sweatshirts', 'Shoes', 'Handbags', 'Accesories', 'Other' ] , :prompt => 'Select a category', class:"form-control", required: "true", class: "form-control"  %>
  </div>
 <div class="field">
   <%= f.label :gender %><br>
   <%= f.select :gender, ['Male', 'Female'] , :prompt => 'Select a category', class:"form-control", required: "true", class: "form-control"  %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price , class: "form-control", required:"true", placeholder:"$"%>
  </div>
  <div class="actions">
    <%= f.submit "Post this Item", class: "btn btn-primary"%>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing item</h1>

<%= render 'form' %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<h1>Listing items</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Image</th>
      <th>Category</th>
      <th>User</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.name %></td>
        <td><%= item.description %></td>
        <td><%= item.image %></td>
        <td><%= item.category %></td>
        <td><%= item.user_id %></td>
        <td><%= item.price %></td>
        <td><%= link_to 'Show', item %></td>
        <td><%= link_to 'Edit', edit_item_path(item) %></td>
        <td><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Item', new_item_path %>

app/views/items/new.html.erb
<div class="col-md-6 col-md-offset-3">
  <h1> New Item </h1>
      <%= render 'form' %>

      <%= link_to 'Back', items_path %>
</div>

app/views/items/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6">
      <%= image_tag @item.image.url(:display), width: '100%', id: "zoom_01" %>

    </div>
    <div class="col-md-6">
      <h1><%=  @item.name.upcase %></h1>
      <hr>
      <p><strong>Price: $<%=  @item.price %></strong></p> Sold by <%= link_to @item.user.name, @item.user %>
      <hr>
      <h3><%=  @item.description %></h3>
      <br><br>
      <%= link_to 'Buy It Now', new_item_order_path(@item) , class: "btn btn-primary", data: {no_turbolink: true} %> <br>

      <% if  current_user== @item.user %>  
      
        <%= link_to 'Edit', edit_item_path(@item) %> | 
      <% end %>
      <%= link_to 'Back', @item.user %>

    </div>
  </div>
</div>
  
<br><br><br>
<div class="container-fluid">
    <div role="tabpanel">

      <!-- Nav tabs -->
      <ul class="nav nav-tabs" role="tablist">
        <li role="presentation" class="active"><a href="#home" aria-controls="home" role="tab" data-toggle="tab">Description</a></li>
        <li role="presentation"><a href="#profile" aria-controls="profile" role="tab" data-toggle="tab">Designer Profile</a></li>
        <li role="presentation"><a href="#messages" aria-controls="messages" role="tab" data-toggle="tab">Reviews</a></li>
        
      </ul>

      <!-- Tab panes -->
      <div class="tab-content">
        <div role="tabpanel" class="tab-pane active container" id="home"><br><%=  @item.description %></div>
        <div role="tabpanel" class="tab-pane container" id="profile"><br><h3><%= link_to @item.user.name, @item.user %></h3>
        <%=  @item.user.bio %>
        </div>
        <div role="tabpanel" class="tab-pane" id="messages"><br>
          <%= form_for Comment.new do |f|   %>
                      <%= f.text_area  :content, class:"form-control", placeholder:"Enter your comment here!", required: true%>
                      <% if user_signed_in? %>
                            <%= f.hidden_field :user_id, value: current_user.id %>
                      <%end %>
                  <%= f.hidden_field :item_id, value: @item.id %>
                    
                      <%= f.submit "Submit this comment", class:"btn btn-primary" %>
                     
                    <% end %>
              <br>
          
              <% @item.comments.order('created_at DESC').each do |com| %>
                    <div class="panel panel-default">
                    <div class="panel-body">
                      <%= com.content  %>
                    </div>
                    <div class="panel-footer"><%= link_to com.user.name, com.user %> on  <%= com.created_at.strftime("%b/%d/%Y") %> at   <%=com.created_at.strftime("%I:%M%p") %></div>
                  </div>
       
                    
                  <% end %>
        
        
        
        
        </div>
        
      </div>

    </div>
</div>

<br><br><br><br><br><br>

<script>
  
  $('#zoom_01').elevateZoom({
    zoomType: "inner",
cursor: "crosshair",
zoomWindowFadeIn: 500,
zoomWindowFadeOut: 750
   }); 
  
</script>



<!-- JS to add -->
<script type="text/javascript">
  $(document).ready(function(){
	$(".basic").jRating();
  });
</script>