config/routes.rb
Rails.application.routes.draw do

  resources :applications

  resources :comments
  resources :orders
  
  resources :items do
    resources :orders
    resources :comments
  end
  
  resources :orders do
    member do
      put "ship", to: "orders#ship"
    end
  end
  
  
  get 'users/show'

  devise_for :users
  
  resources :users
  resources :users do
    member do
      put "join", to: "users#join"
      put "kick", to: "users#kick"
    end
  end

  post "/orders/:id" => "orders#show"
  post "/hook" => "orders#hook"
  
  
  get 'pages/men'
  
  get 'pages/women'
  
  get 'pages/lookbook'
  
  get 'pages/manage'
  
  get 'pages/home'

  get 'pages/about'

  get 'pages/contact'
  
  get 'pages/shop'
  
  get 'pages/join'
  
  get 'pages/meet'
  
  root 'pages#home'
  
   get 'sales' => 'orders#sales'
  
  get 'purchases' => 'orders#purchases'

end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#header">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>

    <div class="collapse navbar-collapse" id="header">
      <ul class="nav navbar-nav">
        
      </ul>

      
      
      <ul class="nav navbar-nav navbar-right">
                                <% if user_signed_in? %>
                                  <li class="dropdown">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Logged in as <%= current_user.name %> <span class="caret"></span></a>
                                    <ul class="dropdown-menu" role="menu">
                                      <li><%= link_to "View Profile", current_user  %></li>
                                      <li><%= link_to "Edit Profile", edit_user_registration_path  %></li>
                                      <li><%= link_to "View Purchases", purchases_path  %></li>
                                     
                                      
                                      <% if current_user.admin == true %>
                                      <li><%= link_to "Manage", pages_manage_path %></li>
                                      <% end %>
                                      <% if current_user.member == true %>
                                      <li><%= link_to "Add an Item", new_item_path %></li>
                                      <li><%= link_to "View Sales", sales_path  %></li>
                                      <% end %>
                                       <li><%= link_to "Log Out", destroy_user_session_path, method: :delete  %></li>
                                    </ul>
                                  </li>
                                <% else %>
                                  <li><%= link_to "Sign up", new_user_registration_path  %></li>
                                  <li><%= link_to "Log in", new_user_session_path  %></li>
                                <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_header2.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#header2">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>

    <div class="collapse navbar-collapse" id="header2">
      <ul class="nav navbar-nav spread">
        <li><%= link_to "HOME", root_path %></li>
        <li><%= link_to "SHOP NOW", pages_shop_path %></li>
        <li><%= link_to "MEET THE DESIGNERS", pages_meet_path %></li>
        <li><%= link_to "JOIN THE CLIQUE", new_application_path %></li>
        <li><%= link_to "CONTACT US", pages_contact_path %></li>
      </ul>
     
      <ul class="nav navbar-nav navbar-right">

      </ul>
    </div>
   
  </div>
</nav>

app/views/layouts/_slider.html.erb
    <!-- Carousel
    ================================================== -->
    <div id="myCarousel" class="carousel slide" data-ride="carousel">
      <!-- Indicators -->
      <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
      </ol>
      <div class="carousel-inner" role="listbox">
        <div class="item active">
          <img class="first-slide" src="http://res.cloudinary.com/bisonshare/image/upload/v1430787227/Join_the_Clique_fmc6tr.jpg" width="100%" alt="First slide">
          <div class="container">
            <div class="carousel-caption">
              <h1><%= link_to "Join the Clique", new_application_path %></h1>
              
            </div>
          </div>
        </div>
        <div class="item">
          <img class="second-slide" src="http://res.cloudinary.com/bisonshare/image/upload/v1431055543/Shop_Now_ream7i.jpg"  width="100%"  alt="Second slide">
          <div class="container">
            <div class="carousel-caption">
              <h1><%= link_to "Shop Now", pages_shop_path %></h1>
            
            </div>
          </div>
        </div>
        <div class="item">
          <img class="third-slide" src="http://res.cloudinary.com/bisonshare/image/upload/v1430518950/Meet_the_Designers_ct8nkb.jpg" width="100%"  alt="Third slide">
          <div class="container">
            <div class="carousel-caption">
             <h1><%= link_to "Meet the Designers", pages_meet_path %></h1>

            </div>
          </div>
        </div>
      </div>
      <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div><!-- /.carousel -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Clique</title>
  <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
  
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>  
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script> 
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'https://js.stripe.com/v2/'  %>
  <%= csrf_meta_tags %>
  
  <%= tag :meta, :name => "stripe-key", :content => ENV["PUBLISHABLE_KEY"] %>
  
  
</head>
<body>
  <%= render 'layouts/header' %>
  <div class="text-center">
    <a href="/"><img src="http://res.cloudinary.com/bisonshare/image/upload/v1426191757/clique_aswr47.png" class="img-responsive text-center" width="300px" ></a>
  </div>
   <%= render 'layouts/header2' %>
  <% if current_page?(root_path) %>  
    <%= render 'layouts/slider' %>
  <% end %>
<div class="container">  

     <p class="notice"><%= notice %></p>                                                                                                                                 
       <p class="alert"><%= alert %></p>  
  <%= yield %>
  <br><br><br><br>
  </div>

  

</body>
</html>